# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CxAngle
                                 A QGIS plugin
 Find CX Angle between input source and RPL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-04-12
        copyright            : (C) 2021 by https://github.com/drefrant
        email                : diensa.refranto@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'https://github.com/drefrant'
__date__ = '2021-04-12'
__copyright__ = '(C) 2021 by https://github.com/drefrant'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CxAngle class from file CxAngle.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cx_angle import CxAnglePlugin
    return CxAnglePlugin()
